/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SimpleBank } from "./SimpleBank";

export { SimpleBank__factory } from "./factories/SimpleBank__factory";
